### ISSUE TITLE
Allow to switch between lightwalletd servers

### ISSUE THREAD

**Issue by HonzaR** [zcash/zcash-android-wallet-sdk#1095]
## Is your feature request related to a problem? Please describe.
Right now the lightwalletd is hardcoded into the SDK but we want to let users of SDK switch between other servers or input a custom one.

Please implement:

- ~~a way how to setup several lightwalletd servers~~
- a way how to switch between them
- ~~a way how to input a custom one~~

For the list of alternatives use (mainnet only!)

| Location | Host | Port |
| --- | --- | --- |
| North America  | [na.lightwalletd.com](http://na.lightwalletd.com/) | 443 |
| South America | [sa.lightwalletd.com](http://sa.lightwalletd.com/) | 443 |
| Europe & Africa | [eu.lightwalletd.com](http://eu.lightwalletd.com/) | 443 |
| Asia & Oceania | [ai.lightwalletd.com](http://ai.lightwalletd.com/) | 443 |

## Describe the solution you'd like
We'll possibly need to provide the network-type object through the persistable wallet object. In most cases, we use `ZcashNetwork.fromResources(application)` API to get the correct network object, which is a wrapper for the host and port setting. An important place to look is the `LightWalletEndpointExt.kt` component.

## Additional context
There is a requirement to have this feature available to public API, so the wallet clients can leverage it. If we plan to allow server switching while we communicate with the previously set server, then we need to stop all related components and reset their state.

**Comment by HonzaR** [comment]
After examining the topic of changing the lightwalletd server via a client app more in detail, we should share this information:
- A client app can change the lightwalletd server when establishing a connection with Synchronizer. Please, see the convenient way how to [create a new Synchronizer](https://github.com/zcash/zcash-android-wallet-sdk/blob/e60af8e824ed9c901815e09a116480228dd5135e/sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt#L418C21-L418C24). The important parameter is the `lightWalletEndpoint: LightWalletEndpoint`, which is a wrapper class for the `host` and `port` values.
- The view-based Demo app uses this approach to create and use Synchronizer for communication to the lightwalletd server in `SharedViewModel`, although there is another way to create Synchronizer, and it's via `WalletCoordinator` which we use in the Secant wallet. We could consider tweaking the WalletCoordinator API to provide a way of setting the lightwalletd server in a parameter.
- Then there one more way, which is even more customizable, and its via creating an instance of `LightWalletClient`, into which anyone can inject their own LightWalletEndpoint object.

**Comment by Mandeepbhalothia** [comment]
I think 3rd option is good where we can inject any custom instance of `LightWalletClient` and  give option via any api to set in  `WalletCoordinator`. 
Will it be requiring to restart the app to start sync again with new server, because now in Secant app we are persisting the WalletCoordinator?

**Comment by daira** [comment]
Is this what you're referring to?
https://github.com/zcash/zcash-android-wallet-sdk/blob/ee28e4cedb2a8225c01f20f5e992614bae6de63a/sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/LightWalletEndpointExt.kt#L29

If so, I believe that constant is only used by `defaultForNetwork`:
https://github.com/zcash/zcash-android-wallet-sdk/blob/ee28e4cedb2a8225c01f20f5e992614bae6de63a/sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/LightWalletEndpointExt.kt#L11-L17
and that it is possible to just not use `defaultForNetwork`. Is there some other issue with that?

**Comment by MandeepDaffo** [comment]
@daira Now we are using WalletCoordinator in app to get synchronizer and there we don't have a way to pass the custom LightWalletEndPoint. So if there is will be a way or api to pass the custom object from client with exiting implementation that will be good. I think that will be minimal changes at client and sdk both.
