### ISSUE TITLE
Send Testnet Transaction fails

### ISSUE THREAD

**Issue by Mandeepbhalothia** [zcash/zcash-android-wallet-sdk#1122]
### Describe the issue
While trying to send on testnet transaction is failing with error.

#### If so, please list the steps to reproduce below:
1. Enter valid amount
2. Enter valid toAddress
3. Call send function to send the amount

### Expected behaviour
It should successfully send the amount and return as a successful transaction.

### Actual behavior + errors
Failing with the below error

`TransactionEncoderImpl.createSpend(): creating transaction to spend Zatoshi(value=10000) zatoshi to ***masked*** with memo [B@6d1f9b7
SaplingParamTool.ensureParams$zcash_android_sdk_1_19_0_beta01_release(): Attempting to download missing params: sapling-spend.params.
TransactionEncoderImpl.createSpend(): Caught exception while creating transaction.
Send fail 
androidx.compose.runtime.LeftCompositionCancellationException: The coroutine scope left the composition`

**Comment by HonzaR** [comment]
Hi @Mandeepbhalothia, please, could you provide more information related to this problem? 

When I try:
1. Clean build and run the Demo-app
2. Select the Alyssa's wallet
3. Let the sync finish 
4. Confirm I see sufficient balance
5. Go to the Send screen
6. Select Ben's address as a destination and fill in the amount with the memo
7. Hit the Send button
8. After a few seconds, I see the successfully sent amount

With log:
```
TransactionEncoderImpl.createSpend(): creating transaction to spend Zatoshi(value=100) zatoshi to ****yhnf with memo [B@97756e8
SaplingParamTool.validate$zcash_android_sdk_1_19_0_beta01_release(): Param files both exist!
TransactionEncoderImpl.createSpend(): params exist! attempting to send...
TransactionEncoderImpl.createSpend(): result of sendToAddress: 19
OutboundTransactionManagerImpl.submit(): SUCCESS: submit transaction completed with response: SendResponseUnsafe(code=0, message="145e0fc74c826c802fb8fd0050b8113cd2246fc610df9687f30dac190aee8322")
```

**Comment by Mandeepbhalothia** [comment]
Hi @HonzaR Thanks for verifying. Now I also cross verified with same sdk I am also able to send the Zec on testnet not sure there was any api changes or not.
