### ISSUE TITLE
Post-v2.0.0-rc1 cleanup to be addressed prior to v2.0.0 release

### ISSUE THREAD

**Issue by nuttycom** [zcash/zcash-android-wallet-sdk#1239]
This issue is to track that comments from https://github.com/zcash/zcash-android-wallet-sdk/pull/1116 that were not resolved prior to the v2.0.0-rc1 release are addressed before v2.0.0 final.

**Comment by daira** [comment]
Not complete because it is blocked by #1241 and #1243. It should be fixed by #1247.
