### ISSUE TITLE
ScanRange should fail when no matching priority

### ISSUE THREAD

**Issue by LukasKorba** [zcash/zcash-android-wallet-sdk#1242]
The priorities for scan range are given so any attempt to initialize ScanRange with unsupported value should fail (fatalError)

**Comment by nuttycom** [comment]
Moving this out of 2.0.0 because there is no way for the Rust library to provide the Android SDK with an invalid result. It should still be fixed, but given the objective to minimize the diff between 2.0.0-rc1 and 2.0.0 we don't need to do this now.
