### ISSUE TITLE
Android Reorg Test: Outbound Reorg Tests

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#125]
Create a test class that verifies outbound transactions.

Test Cases:
- [ ] [Outbound TX] Index of TX changes in block
- - Verify: Transaction is present in a block with Index X
- - Verify: Reorg occurs and transaction is present in the same block with index Y where Y != X
- [ ] [Outbound TX] Change of block height for a transaction
- - Verify: Transaction is present in a block with height X
- - Verify: Reorg occurs and transaction is not present in block X and the SDK considers it `pending`
- - Verify: Transaction shows up in another block with height Y where Y > X + 1 and the SDK considers it `confirmed`
- [ ] [Outbound TX] Last transaction disappears and is mined later
- - Verify: Transaction is mined in a block X and the SDK considers it `confirmed`
- - Verify: Reorg occurs and transaction goes away and is mined later so SDK now considers it "Pending"

**Comment by braddmiller** [comment]
Warning: Exercise the connection with darksidewalletd early because some of these APIs have not been used/verified yet, specifically the ones around spending behavior. Bump points to account for uncertainty and allow integration time.
