### ISSUE TITLE
Remove Dependency on NovaCrypto Libraries

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet-sdk#129]
Remove the dependency on Novacrypto libraries BIP39 and Secure String in the Android SDK and Wallet and replace with libraries of choice or a custom implementation with licenses compatible with MIT.

**Comment by gmale** [comment]
Considering an custom implementation and began the shell of one here:
https://github.com/zcash/android-bip39 and will run it by Sean for the hard parts. Can't quite give a meaningful estimate but at a high level I need to:

- generate entropy [done] (t-shirt size: small)
- convert entropy into mnemonic phrase [in-progress] (t-shirt size: medium)
- convert phrase into seed (t-shirt size: large)
- (optional) derive entropy from mnemonic (t-shirt size: TBD)

Over the weekend, I found and read through [the reference implementation from trezor](https://github.com/trezor/python-mnemonic/blob/master/mnemonic/mnemonic.py) and the implementation _they_ referenced [from bitcoinj](https://github.com/bitcoinj/bitcoinj/blob/6aa4e51de6004f7171802bbce9c1660228d05aae/core/src/main/java/org/bitcoinj/crypto/MnemonicCode.java#L147), which is pretty easy to understand so this task mostly involves porting that to Kotlin.

Key questions will be whether 3rd party libraries are still required for some of the more complex portions and whether we want to support all word-lengths and languages.

**Comment by gmale** [comment]
for seed creation (bullet 3) just need to find a good source for `PBKDF2SHA512` then this becomes easy.

for entropy derivation (bullet 4) we just do bullet 2 in reverse. So this isn't so bad.

**Comment by gmale** [comment]
found a kotlin implementation of pbkdf2:
https://github.com/horizontalsystems/hd-wallet-kit-android/blob/ddf3c48f575ac3b816e0c325f520e9d3854a8cc5/src/main/kotlin/io/horizontalsystems/hdwalletkit/PBKDFSHA512.kt

**Comment by gmale** [comment]
Initial implementation is feature complete and published to bintray.

**Comment by gmale** [comment]
wallet has been updated to [remove novacrypto in favor of new implementation](https://github.com/zcash/zcash-android-wallet/pull/146)
