### ISSUE TITLE
Checkpoint creator is broken and needs maintenance

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#157]
The tool we use to create checkpoints ([sapling updater](https://github.com/zcash/zcash-android-wallet-sdk/blob/master/src/main/rust/bin/update_sapling_tree.rs)) is no longer working on the latest builds. The error is related to version resolution among dependencies.

Running it fails with the following error:
```bash
$ cd /path/to/zcash-android-wallet-sdk/
$ cargo run --release --features=updater,mainnet 921150
  --> /home/gmale/.cargo/registry/src/github.com-1ecc6299db9ec823/grpc-0.6.1/src/protobuf.rs:21:62
   |
21 |         let mut is = CodedInputStream::from_carllerche_bytes(&buf);
   |                                                              ^^^^ expected struct `bytes::bytes::Bytes`, found struct `bytes::Bytes`
```

It still works if I roll back to commit 92f34e5

The major difference in that commit is the grpc version `0.6.1` v. `0.6.2` and the protobuf version `2.14.0` v. `2.8.2` per the following lock file diff. The broken code uses protobuf `2.14.0` and the latest version of that library is greater (2.17 IIRC):
![Screenshot from 2020-08-12 12-05-32](https://user-images.githubusercontent.com/1699841/90282999-63629d80-de3d-11ea-9db0-b9a8c31a5cb3.png)

**Comment by pacu** [comment]
We should probably extract this to its own repo.

**Comment by gmale** [comment]
Agreed or move it to a more fitting repo inside of librustzcash

**Comment by gmale** [comment]
Looks like this issue is appearing on the iOS side, as well.

**Comment by gmale** [comment]
Fixed as part of the rust crate updates https://github.com/zcash/zcash-android-wallet-sdk/pull/164
