### ISSUE TITLE
Feature Request: Quick Restore

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#158]
As a user, I'd like to be able to quickly restore my wallet without having to resync the whole chain.

**Criteria**
- [ ] ideally, this quick restore can happen in less than a second
- [ ] ideally, if I've synced my wallet once, I don't have to pay that price ever again

**Comment by nighthawk24** [comment]
Would this speed up the new wallet creation? As of not, when a user creates a new wallet, the app still needs to sync.

**Comment by gmale** [comment]
New wallet creation is sped up by making newer checkpoints. Eventually, new checkpoints might be provided by a service. Generally speaking, restoring a wallet is the most painful thing.

**Comment by ccjernigan** [comment]
Closing in favor of current work to improve sync performance.
