### ISSUE TITLE
Ability to create t-addresses in librustzcash

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet-sdk#167]
As a developer I would like to be able to create t-addresses and their associated keys by passing an existing seed phrase to librustzcash.

Notes:
This will require a PR back to LRZ and multiple rounds or revision and review.

**Comment by gmale** [comment]
This will boil down to 2 units of work:

1. generating the private key
2. generating the address

// TODO add more detail

**Comment by gmale** [comment]
At this point, @pacu has done a bunch of work in this area and we can just combine efforts. The main thing remaining on the Android side would be storing and managing the secret key that gets created (as well as creating a function in the derivationTool to return a secret key, given a seed).

As part of this work, we can take some of the code from the welding layer and move it down into librustzcash.
