### ISSUE TITLE
Add support for ZIP 313

### ISSUE THREAD

**Issue by nighthawk24** [zcash/zcash-android-wallet-sdk#174]
ZIP 313 changes the default/conventional fee for shielded transactions from 10,000 zats to 1,000 zats
[https://github.com/zcash/zips/pull/408](url)

To implement this change, the SDK default fee needs to be changed from 10,000 to 1,000 zats for shielded transactions. This change might also need updates in the rust lib code.

Activation: The recommended fee of 0.00001 or 1000 zats must be activated at block 1046400 to coincide with the `Canopy upgrade. <https://z.cash/upgrade/canopy/>`
With a grace period of ~4 weeks (block 1080000) to upgrade to the reduced default transaction fee for zcashd and core clients used by exchanges & service providers.

The implementation to activate the new fee can start anytime from the start to the end of the 4 week transition period outside which the shielded transaction fees will stand out from the updated light client fees of 1000 zats.

**Comment by gmale** [comment]
Hopefully, no changes necessary in this project and everything is inherited from librustzcash but we'll need to confirm.

**Comment by braddmiller** [comment]
Our plan is to implement the data access API prior to adding ZIP 313, this will allow us to easily calculate the fee and surface it to users as opposed to hardcoding in the UI. Goal is to implement prior to the 4 week grace period expiring.

**Comment by braddmiller** [comment]
Our plan is to implement the data access API prior to adding ZIP 313, this will allow us to easily calculate the fee and surface it to users as opposed to hardcoding in the UI. Goal is to implement prior to the 4 week grace period expiring.

**Comment by gmale** [comment]
This is complete and also functional in the latest build of the ECC Wallet.
