### ISSUE TITLE
Demo app: resuming app on scanning step

### ISSUE THREAD

**Issue by samosudov** [zcash/zcash-android-wallet-sdk#175]
**What is the bug?**
In the menu _List of transactions_ I had _Scanning_ status of wallet.
My phone's screen turned off after a minute.
After some time I turned on the phone and app was resumed and crashed at the same time.

**Additional context**
Log of the crash:

> 2020-11-06 15:36:17.434 9077-9794/cash.z.ecc.android.sdk.demoapp.mainnet W/System.err: @TWIG 11/06/20 03:36:17.433000000[CompactBlockProcessor:738](#scanning)    batch scanned: 973950/1032624
> 2020-11-06 15:36:21.017 9077-9794/cash.z.ecc.android.sdk.demoapp.mainnet W/System.err: @TWIG 11/06/20 03:36:21.016000000[CompactBlockProcessor:738](#scanning)    batch scanned: 974100/1032624
> 2020-11-06 15:36:25.831 9077-9077/cash.z.ecc.android.sdk.demoapp.mainnet D/AndroidRuntime: Shutting down VM
> 2020-11-06 15:36:25.853 9077-9077/cash.z.ecc.android.sdk.demoapp.mainnet E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: cash.z.ecc.android.sdk.demoapp.mainnet, PID: 9077
>     java.lang.RuntimeException: Unable to resume activity {cash.z.ecc.android.sdk.demoapp.mainnet/cash.z.ecc.android.sdk.demoapp.MainActivity}: cash.z.ecc.android.sdk.exception.SynchronizerException$FalseStart: This synchronizer was already started. Multiple calls to start are notallowed and once a synchronizer has stopped it cannot be restarted.
>         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
>         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6494)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
>      Caused by: cash.z.ecc.android.sdk.exception.SynchronizerException$FalseStart: This synchronizer was already started. Multiple calls to start are notallowed and once a synchronizer has stopped it cannot be restarted.
>         at cash.z.ecc.android.sdk.SdkSynchronizer.start(SdkSynchronizer.kt:193)
>         at cash.z.ecc.android.sdk.demoapp.demos.listtransactions.ListTransactionsFragment.onResume(ListTransactionsFragment.kt:137)
>         at androidx.fragment.app.Fragment.performResume(Fragment.java:3011)
>         at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:614)
>         at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:314)
>         at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
>         at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1632)
>         at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3109)
>         at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3067)
>         at androidx.fragment.app.Fragment.performResume(Fragment.java:3020)
>         at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:614)
>         at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:314)
>         at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
>         at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1632)
>         at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3109)
>         at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3067)
>         at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
>         at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:434)
>         at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:423)
>         at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
>         at android.app.Activity.performResume(Activity.java:7141)
>         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
>         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:164) 
>         at android.app.ActivityThread.main(ActivityThread.java:6494) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
> 2020-11-06 15:36:25.888 765-3545/? W/ActivityManager:   Force finishing activity cash.z.ecc.android.sdk.demoapp.mainnet/cash.z.ecc.android.sdk.demoapp.MainActivity
> 2020-11-06 15:36:25.923 765-780/? I/ActivityManager: Showing crash dialog for package cash.z.ecc.android.sdk.demoapp.mainnet u0
> 2020-11-06 15:36:26.343 9077-9794/cash.z.ecc.android.sdk.demoapp.mainnet W/System.err: @TWIG 11/06/20 03:36:26.341000000[CompactBlockProcessor:738](#scanning)    batch scanned: 974250/1032624
> 2020-11-06 15:36:26.390 765-779/? W/ActivityManager: Activity pause timeout for ActivityRecord{34d418c u0 cash.z.ecc.android.sdk.demoapp.mainnet/cash.z.ecc.android.sdk.demoapp.MainActivity t1291 f}
> 2020-11-06 15:36:27.522 765-1225/? I/WindowManager: Failed to capture screenshot of Token{25c0d5 ActivityRecord{34d418c u0 cash.z.ecc.android.sdk.demoapp.mainnet/cash.z.ecc.android.sdk.demoapp.MainActivity t1291 f}} appWin=Window{9b50e80 u0 SnapshotStartingWindow for taskId=1291 EXITING} drawState=4
> 2020-11-06 15:36:38.346 765-779/? W/ActivityManager: Activity destroy timeout for ActivityRecord{34d418c u0 cash.z.ecc.android.sdk.demoapp.mainnet/cash.z.ecc.android.sdk.demoapp.MainActivity t1291 f}
> 2020-11-06 15:36:48.502 9077-9794/cash.z.ecc.android.sdk.demoapp.mainnet W/System.err: @TWIG 11/06/20 03:36:48.501000000[CompactBlockProcessor:738](#scanning)    batch scanned: 974400/1032624
> 2020-11-06 15:36:59.311 765-3581/? I/ActivityManager: Process cash.z.ecc.android.sdk.demoapp.mainnet (pid 9077) has died: cch+6CEM 
> 2020-11-06 15:36:59.326 765-3545/? W/ActivityManager: Ignoring remove of inactive process: ProcessRecord{13345f5 0:cash.z.ecc.android.sdk.demoapp.mainnet/u0a1674}

**Comment by gmale** [comment]
Thanks for reporting this. I've looked into it and I think I'm okay with this crash . . . only because it is a demo app. When the app is reopened after the crash it picks up where it left off and works fine. Also, it continues syncing in the background, it just doesn't like to be restarted.

I don't think it's worth it to put energy into making the demo app super robust because it's only purpose is to give some quick examples of things working.

It might make sense to make the synchronizer lifecycle-aware but doing that well is a fairly large task.

The workaround here is to just relaunch the demo.

**Comment by gmale** [comment]
After thinking about this a bit more I think we can leave this issue open and tackle it as part of the upcoming [background sync](https://github.com/zcash/zcash-android-wallet/issues/201) work. Synchronizers can become lifecycle-aware since [that library](https://developer.android.com/topic/libraries/architecture/lifecycle) is already a dependency of the SDK. This will allow us to address when and how background work is queued whenever the app is not in the foreground.

**Comment by ccjernigan** [comment]
We're migrating to a new demo app based on compose, so issues for the older UI aren't relevant.
