### ISSUE TITLE
Demo app: UTXO menu - crash on Load transaction button

### ISSUE THREAD

**Issue by samosudov** [zcash/zcash-android-wallet-sdk#176]
**What is the bug?**
After wallet scanning was finished I tapped on UTXO menu item.
No one screen parameters was changed.
I tapped on button `Load transactions` and app was crashed.

**Additional context**
Log of the crash:

> 2020-11-06 16:14:35.212 18781-18781/cash.z.ecc.android.sdk.demoapp.mainnet W/System.err: @TWIG 11/06/20 04:14:35.210000000[ListUtxosFragment:252](#)    loading transactions in range 419200..968085
> 2020-11-06 16:14:35.337 32707-30986/? W/kwp: Infinite Data has no result for cash.z.ecc.android.sdk.demoapp.mainnet [CONTEXT service_id=177 ]
> 2020-11-06 16:14:35.451 32707-2809/? W/kwp: Infinite Data has no result for cash.z.ecc.android.sdk.demoapp.mainnet [CONTEXT service_id=177 ]
> 2020-11-06 16:14:35.943 18781-18781/cash.z.ecc.android.sdk.demoapp.mainnet D/AndroidRuntime: Shutting down VM
> 2020-11-06 16:14:35.953 18781-18781/cash.z.ecc.android.sdk.demoapp.mainnet E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: cash.z.ecc.android.sdk.demoapp.mainnet, PID: 18781
>     io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown method GetAddressTxids for service cash.z.wallet.sdk.rpc.CompactTxStreamer
>         at io.grpc.Status.asRuntimeException(Status.java:533)
>         at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:604)
>         at cash.z.ecc.android.sdk.service.LightWalletGrpcService.toList(LightWalletGrpcService.kt:160)
>         at cash.z.ecc.android.sdk.service.LightWalletGrpcService.getTAddressTransactions(LightWalletGrpcService.kt:120)
>         at cash.z.ecc.android.sdk.demoapp.demos.listutxos.ListUtxosFragment$downloadTransactions$1.run(ListUtxosFragment.kt:104)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6494)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> 2020-11-06 16:14:35.962 765-9985/? W/ActivityManager:   Force finishing activity cash.z.ecc.android.sdk.demoapp.mainnet/cash.z.ecc.android.sdk.demoapp.MainActivity
> 2020-11-06 16:14:35.978 765-780/? I/ActivityManager: Showing crash dialog for package cash.z.ecc.android.sdk.demoapp.mainnet u0

**Comment by gmale** [comment]
This seems to be caused by `GetAddressTxids` being changed to [GetTAddressTxids](https://github.com/zcash/lightwalletd/blob/master/walletrpc/service.proto#L146) but that change happened a long time ago. I'll look into why this seems to still point to the old version.

**Comment by gmale** [comment]
Found and fixed the problem. This will work in the next release.
