### ISSUE TITLE
Clear the build warnings

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#184]
There are quite a lot of build warnings on the SDK.  Most of them can be cleared by applying the `ExperimentalCoroutinesApi` compiler argument to the build.

This ticket tracks the warnings as they currently exist and provides a placeholder for reducing them, over time.

**Comment by gmale** [comment]
current list of warnings:

>> Task :compileZcashmainnetDebugKotlin
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (17, 70): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (17, 86): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (18, 18): This declaration overrides experimental member of supertype 'SdkInitializer' and should be annotated with '@kotlinx.coroutines.ExperimentalCoroutinesApi'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (18, 18): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (19, 18): This declaration overrides experimental member of supertype 'SdkInitializer' and should be annotated with '@kotlinx.coroutines.ExperimentalCoroutinesApi'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (19, 18): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (20, 18): This declaration overrides experimental member of supertype 'SdkInitializer' and should be annotated with '@kotlinx.coroutines.ExperimentalCoroutinesApi'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (20, 18): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (21, 18): This declaration overrides experimental member of supertype 'SdkInitializer' and should be annotated with '@kotlinx.coroutines.ExperimentalCoroutinesApi'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (21, 18): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (22, 18): This declaration overrides experimental member of supertype 'SdkInitializer' and should be annotated with '@kotlinx.coroutines.ExperimentalCoroutinesApi'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (22, 18): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (315, 24): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (315, 40): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (330, 22): This declaration overrides experimental member of supertype 'Erasable' and should be annotated with '@kotlinx.coroutines.ExperimentalCoroutinesApi'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/Initializer.kt: (330, 22): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (304, 33): Parameter 'unused' is never used
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (360, 40): Parameter 'scannedRange' is never used
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (476, 21): The expression is unused
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (587, 18): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (587, 34): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (589, 48): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (589, 75): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (590, 69): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (590, 90): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (591, 70): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (591, 91): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (591, 109): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (592, 72): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (595, 50): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (597, 67): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (597, 92): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt: (602, 12): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (76, 25): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (76, 60): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (77, 29): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (78, 34): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (91, 24): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (97, 30): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (103, 40): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (136, 38): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (136, 64): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (254, 17): Condition 'newTxs == null' is always 'false'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (260, 19): Unnecessary safe call on a non-null receiver of type List<ConfirmedTransaction>
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (261, 21): Condition 'newTransaction == null' is always 'false'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (312, 20): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (331, 31): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (338, 19): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (431, 24): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (502, 39): Parameter 'fastIntervalDesired' is never used
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt: (563, 16): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/db/DerivedDataDb.kt: (349, 33): Variable 'hasFinalMatch' initializer is redundant
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/db/entity/Transactions.kt: (291, 40): Condition 'other.rawTransactionId != null' is always 'true'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (50, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (68, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (86, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (104, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (126, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (144, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (165, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (179, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (198, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (215, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (228, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (241, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (257, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (269, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (286, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (307, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (320, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (340, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (352, 10): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/CurrencyFormatter.kt: (361, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/Twig.kt: (75, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/Twig.kt: (171, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/android/ComputableFlow.kt: (12, 37): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/android/ComputableFlow.kt: (12, 68): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/android/ComputableFlow.kt: (13, 44): This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with '@kotlinx.coroutines.FlowPreview' or '@OptIn(kotlinx.coroutines.FlowPreview::class)' if you accept the drawback of relying on preview API
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/android/ComputableFlow.kt: (13, 72): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/android/ComputableFlow.kt: (22, 54): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/android/ComputableFlow.kt: (27, 28): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/android/FlowPagedList.kt: (53, 1): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/ext/android/FlowPagedListBuilder.kt: (59, 50): Unchecked cast: Any? to Key
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/service/LightWalletGrpcService.kt: (145, 13): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/service/LightWalletGrpcService.kt: (148, 13): Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of functional types
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/tool/DerivationTool.kt: (82, 32): Parameter 'viewingKey' is never used
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/transaction/PersistentTransactionManager.kt: (70, 9): The corresponding parameter in the supertype 'OutboundTransactionManager' is named 'zatoshi'. This may cause problems when calling this function with named arguments.
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/transaction/PersistentTransactionManager.kt: (222, 32): The corresponding parameter in the supertype 'OutboundTransactionManager' is named 'it'. This may cause problems when calling this function with named arguments.
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt: (178, 20): Unsafe use of a nullable receiver of type File?
w: /home/gmale/kg/work/clones/zcash-android-wallet-sdk/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt: (182, 21): Unsafe use of a nullable receiver of type File?

**Comment by herou** [comment]
@gmale I created a PR for this issue #187 Please, check it and let me know.

**Comment by herou** [comment]
@gmale Any other ticket which I can take care of?

**Comment by gmale** [comment]
Warnings have been reduced from the above list to the following:

```
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/ext/TestExtensions.kt: (30, 55): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ObsoleteCoroutinesApi' or '@OptIn(kotlinx.coroutines.ObsoleteCoroutinesApi::class)'
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/ext/TestExtensions.kt: (58, 35): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ObsoleteCoroutinesApi' or '@OptIn(kotlinx.coroutines.ObsoleteCoroutinesApi::class)'
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/ext/TestExtensions.kt: (58, 69): The resulting type of this 'javaClass' call is Class<ScopedTest.Companion> and not Class<ScopedTest>. Please use the more clear '::class.java' syntax to avoid confusion
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/integration/reorgs/InboundTxTests.kt: (41, 13): Variable 'overwriteBlockCount' is never used
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/transaction/PersistentTransactionManagerTest.kt: (52, 28): 'initMocks(Any!): Unit' is deprecated. Deprecated in Java
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/transaction/PersistentTransactionManagerTest.kt: (56, 28): Parameter 'invocation' is never used, could be renamed to _
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/util/DarksideTestCoordinator.kt: (76, 37): No cast needed
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/util/DarksideTestCoordinator.kt: (103, 64): No cast needed
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/util/DarksideTestCoordinator.kt: (109, 57): No cast needed
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/util/DarksideTestCoordinator.kt: (155, 38): No cast needed
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/util/DarksideTestCoordinator.kt: (156, 38): No cast needed
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/util/DarksideTestCoordinator.kt: (195, 38): No cast needed
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/util/DarksideTestCoordinator.kt: (206, 41): No cast needed
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/util/SimpleMnemonics.kt: (15, 31): The corresponding parameter in the supertype 'MnemonicPlugin' is named 'seed'. This may cause problems when calling this function with named arguments.
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTest/java/cash/z/ecc/android/sdk/util/SimpleMnemonics.kt: (17, 35): The corresponding parameter in the supertype 'MnemonicPlugin' is named 'seed'. This may cause problems when calling this function with named arguments.
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTestZcashmainnet/java/cash/z/ecc/android/sdk/integration/IntegrationTest.kt: (42, 22): Variable 'hash' is never used
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTestZcashmainnet/java/cash/z/ecc/android/sdk/integration/IntegrationTest.kt: (42, 28): Variable 'time' is never used
w: /home/gmale/kg/work/android-new/zcash-android-wallet-sdk/src/androidTestZcashmainnet/java/cash/z/ecc/android/sdk/integration/IntegrationTest.kt: (42, 34): Variable 'tree' is never used
```

Which is down to 18 from 90, which is an 80% reduction! Nice work!
