### ISSUE TITLE
Add KLint to the project

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#185]
Pinterest has a [great library](https://github.com/pinterest/ktlint) for linting the code and enforcing code style. It would be good to add this to the SDK.

**Comment by nighthawk24** [comment]
I can take care of this.

**Comment by gmale** [comment]
Update: chatted w/ @nighthawk24 and he mentioned work on this is under way! There might be merge conflicts with changes that are in flight but we'll cross that bridge when we get there.

**Comment by nighthawk24** [comment]
Good to close wrt https://github.com/zcash/zcash-android-wallet-sdk/pull/207
