### ISSUE TITLE
Test: Param download behavior when storage is low

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#202]
**As a** library developer, **I'd like to** test what happens when the library attempts to download parameter files on a device that does not have enough storage space **so that** I can confirm that the library exposes this problem clearly and as early as possible.

This issue falls under [the parent issue for param files](https://github.com/zcash/zcash-android-wallet-sdk/issues/201).

### Expected behavior

Note: the param files are expected to exist in the `params` folder of the cache directory:
```kotlin
"${context.cacheDir.absolutePath}/params"
```

## Test Case 1a:
**Given** a device where neither param file exists
**When** the validate function is called
**Then** it returns false

## Test Case 1b:
**Given** a device where the `Spend` params file exists in the expected directory but the `Output` params file does not
**When** the validate function is called
**Then** it returns false

## Test Case 1c:
**Given** a device where the `Output` params file exists in the expected directory but the `Spend` params file does not
**When** the validate function is called
**Then** it returns false

## Test Case 2:
**Given** a device with insufficient storage for both files
**When** the parameter files are downloaded
**Then** it fails with a descriptive error (such as "insufficient storage")

## Test Case 3:
**Given** a device with sufficient storage for only one of the two param files
**When** the parameter files are downloaded
**Then** it fails with a descriptive error (such as "insufficient storage")
&nbsp;&nbsp;  **And** the smaller of the two files has been successfully downloaded

### Criteria
- Repeatable tests exist that confirm the expected behavior
- It is okay for these tests to FAIL right now. **Correcting failures is out of scope for this ticket.**
- Ideally, this test can run on any device, regardless of whether the device has low storage space
  - One way to achieve that might be to mock a call that checks the available disk storage, beforehand

**Comment by gmale** [comment]
Note: this test is a decent example to follow. It's the most recent test written in the SDK:

https://github.com/zcash/zcash-android-wallet-sdk/blob/master/src/androidTest/java/cash/z/ecc/android/sdk/integration/service/ChangeServiceTest.kt

**Comment by herou** [comment]
@gmale assign it to me when you can.

**Comment by gmale** [comment]
to create a context:

```kotlin
val context: Context = InstrumentationRegistry.getInstrumentation().context
```

**Comment by herou** [comment]
@gmale You have it: #211

**Comment by herou** [comment]
@gmale This needs to be closed.
