### ISSUE TITLE
Create SaplingParamTool and add a function for clearing the param files from cache

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#204]
**As an** app developer, **I'd like to** have a tool for working with sapling parameter files **so that** I can more easily manage them and perform common tasks like downloading them when they're missing and clearing them when they're invalid. 

This issue falls under [the parent issue for param files](https://github.com/zcash/zcash-android-wallet-sdk/issues/201).

### Context
The Sapling Parameter files are necessary for creating transactions. They're [explained here in great detail](https://z.cash/technology/paramgen/). For our purposes, they're rather large and need to be present on device prior to sending funds so we download them into the app's cache. The user can clear these files to temporarily reclaim space but they'll be fetched again during the next send.

The "Param files" are two files named `sapling-output.params` (about 3.6 MB) and `sapling-spend.params` (about 48 MB).

Currently, there are two main functions that mange these files:
- [ensureParams](https://github.com/zcash/zcash-android-wallet-sdk/blob/2415bac043e8fd731f307699b312a1774fcc0d45/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt#L134-L155)
- [fetchParams](https://github.com/zcash/zcash-android-wallet-sdk/blob/2415bac043e8fd731f307699b312a1774fcc0d45/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt#L165-L195)

Since we've gotten to the point where we need to add a few more functions for parameter files, this would be a good time to create a helper tool to make that  easier.

### Implementation Details

- [x] Create SaplingParamTool in the same package as [DerivationTool](https://github.com/zcash/zcash-android-wallet-sdk/blob/2415bac043e8fd731f307699b312a1774fcc0d45/src/main/java/cash/z/ecc/android/sdk/tool/DerivationTool.kt)
- [x] Migrate the [ensureParams](https://github.com/zcash/zcash-android-wallet-sdk/blob/2415bac043e8fd731f307699b312a1774fcc0d45/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt#L134-L155) function from [WalletTransactionEncoder](https://github.com/zcash/zcash-android-wallet-sdk/blob/2415bac043e8fd731f307699b312a1774fcc0d45/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt) to SaplingParamTool
- [x] Migrate the [fetchParams](https://github.com/zcash/zcash-android-wallet-sdk/blob/2415bac043e8fd731f307699b312a1774fcc0d45/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt#L165-L195) function (and createHttpClient) from [WalletTransactionEncoder](https://github.com/zcash/zcash-android-wallet-sdk/blob/2415bac043e8fd731f307699b312a1774fcc0d45/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt) to SaplingParamTool
- [x] Clean up [WalletTransactionEncoder](https://github.com/zcash/zcash-android-wallet-sdk/blob/2415bac043e8fd731f307699b312a1774fcc0d45/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt) so that it is only using the tool (statically in the same way that DerivationTool is used)
- [x] Add `SaplingParamTool.clear` function to remove the param files
- [x] Add `SaplingParamTool.validate` function that returns true when the files exist (later, in a separate issue, we will expand this to fully validate the contents, as well)

### Criteria
- A tool exists that can clear the param files from cache
- All existing code that interacts with params now uses the tool instead
- Behavior mirrors DerivationTool--functions are called statically

**Comment by herou** [comment]
@gmale Assign this to me.

**Comment by gmale** [comment]
I'm still working on it :grin:

**Comment by herou** [comment]
@gmale This issue should be closed.

**Comment by herou** [comment]
@gmale This needs to be close since it's merged.
