### ISSUE TITLE
Add a function to SaplingParamTool for verifying the checksum of sapling parameter files

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#205]
This issue is blocked by #204 because the tool needs to exist first before we can add to it.

**As an** app developer, **I'd like to** validate the checksum of sapling parameter files **so that** I can create a better experience for users when these files are invalid and need to be fetched by informing them.

This issue falls under [the parent issue for param files](https://github.com/zcash/zcash-android-wallet-sdk/issues/201).

### Context
If anything goes wrong while downloading the param files, then the simplest fix is to fetch them again. Users can achieve this by clearing the app cache or app developers can do this automatically. Either way, having a function to determine that the files are corrupt (or truncated or otherwise invalid) is useful.

### Implementation Details

- [ ] Expose a function in the RustWelding layer that can perform a checksum of the param files
    - [ ] optional: be able to confirm each file separately so that wallets don't always download both when one is bad
- [ ] Add a function (or two functions such as `validateOutputParamChecksum()` and `validateSpendingParamChecksum()`) to the `SaplingParamTool` that calls this new rust function
- [ ] Update the `SaplingParamTool.validate()` function so that it fails when one or both of the param files have an invalid checksum

Note: Ensuring that the RustBackend is properly loaded at the right time and available to the tool could get tricky.
Note: Hopefully, there is a suitable function in librustzcash that we can call that returns helpful errors that we can map in the SDK. Then this may be as simple as calling `validateSaplingParams` or something similar in the RustBackend.

### Criteria
- A function exists in SaplingParamTool that returns false (or throws an exception) when the param files have an invalid checksum
- Behavior mirrors DerivationTool--functions are called statically
- The `SaplingParamTool.validate()` function fails when the param files exist but have an invalid checksum. Currently, [the function only checks that the files exist](https://github.com/zcash/zcash-android-wallet-sdk/blob/96da0a9beaa92597bd4abdd74dce7c3098fbb86d/src/main/java/cash/z/ecc/android/sdk/tool/SaplingParamTool.kt#L106-L115).

**Comment by ccjernigan** [comment]
This was implemented by Honza.
