### ISSUE TITLE
No setup instructions for lightwalletd

### ISSUE THREAD

**Issue by radix42** [zcash/zcash-android-wallet-sdk#21]
The lack of a README and build/setup instructions for lightwalletd, which I am assuming is the one in the repo under the zcash-hackworks org, is being a major stumbling block right now to trying to use this code in any way.

If there are any docs for how to get that running, a pointer to them would be appreciated.

Thanks.

**Comment by gmale** [comment]
Thanks for the feedback. Yes, this is an early preview. Documentation is one of the many things that is in the works.

**Comment by radix42** [comment]
A minimal "install me like this" README for each of the pieces would
be a great start

**Comment by str4d** [comment]
Migrating this issue to the lightwalletd issue tracker: https://github.com/zcash-hackworks/lightwalletd/issues/26
