### ISSUE TITLE
Migrate "master" branch to "main"

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#237]
As a repository maintainer, I'd like to switch the default branch to "main" instead of "master" in order to better align with github's [updated default branch name for new repositories](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/)

Implementation details:
- follow the github documentation for updating the master branch to main
    * https://github.com/github/renaming/
    * https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by ccjernigan** [comment]
This was implemented #546
