### ISSUE TITLE
Update the Syncrhonizer API to use StateFlow liberally

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#241]
As a wallet developer, I'd like to use StateFlows as much as possible because they are a better replacement for livedata (and similar workflows) than Flows.

Criteria:
- pretty much every `Flow` in the [Synchronizer interface](https://github.com/zcash/zcash-android-wallet-sdk/blob/25982da91de70bcbd09600bba9c2a8c09396a62d/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt) should be replaced with a `StateFlow` as was [recently done](https://github.com/zcash/zcash-android-wallet-sdk/pull/232/files) with balances

Background:
- Originally most things in the Synchronizer API were channels
- When flows came out we switched over because they are an improvement over channels, which should be [considered as communication primitives](https://elizarov.medium.com/?p=899b675e805c) (i.e. not something to expose everywhere) per the [various writings of Roman Elizarov](https://elizarov.medium.com/) the Kotlin/Coroutine Lead.
- [StateFlows](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/) now exist and are a significant improvement and simplification. They can be considered a direct replacement for LiveData (without the lifecycle awareness, but that can be gained by structured concurrency)

**Comment by ccjernigan** [comment]
This migration was done already.
