### ISSUE TITLE
Incorporate the Paging3 library

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#242]
As a wallet developer, I'd like paging to be easy to use in the SDK so that I can display transactions efficiently in the wallet.

Background:
- Paging is currently broken! Therefore this bug is labeled as high-severity.
    - It relies on a [class that I had been told would be moved into Android](https://github.com/zcash/zcash-android-wallet-sdk/tree/296782286b473c309764e6f26ac0bf6711880302/src/main/java/cash/z/ecc/android/sdk/ext/android) but there's a bug
    - We are [passing in 1000 as the "page size"](https://github.com/zcash/zcash-android-wallet-sdk/blob/4586e07cac5d431d0c6842a62d69a0de5036547c/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt#L789) to mask the fact that paging is broken!!!
    - We should be passing something more reasonable like 10 (the number that can fit on one or two screens of the app)
- I was [contemplating writing a component myself ](https://androidstudygroup.slack.com/archives/C5ELAPJC9/p1572878898076000) until I found out that [Chris Banes created basically the same thing](https://twitter.com/chrisbanes/status/1160858967532163072?s=20) so I switched to his implementation of a paging datasource that was compatible with flows
- At the time the maintainers of the Paging library said they were working on a complete overhaul:
    > we're working on a Coroutine-first overhaul of the Paging library, with the focus and benefits more on moving the loading APIs (DataSource) to coroutines. We're planning to natively support flow.

Criteria:
- leverages the new Paging 3 library
- paging is easy and intuitive
- paging is no longer broken

**Comment by ccjernigan** [comment]
If we implement paging, it will be done as paging primitives on the public API rather than using the Paging library.  We don't want our public API to be tightly coupled with Google.
