### ISSUE TITLE
Prevent developers from downloading the sapling parameter files to an insecure location

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#244]
As an SDK developer, I'd like to help wallet developers not shoot themselves in the foot by storing param files in directories that can be easily accessed by other apps or attackers because this is a very nuanced implementation detail of the Sapling protocol that newcomers may not understand.

**Criteria**
- [ ] Developers using the SDK, who provide an external storage directory to the `SaplingParamTool` get at least a warning but preferably an error
- [ ] A test exists to prevent regressions in this area. Such a test should probably work at a level higher than the SaplingParamTool (i.e. create a synchronizer using the highest level APIs possible that attempts to store the params in an external directory) so that if the tool goes away, the regression test still catches this issue.
- [ ] optional (but recommended): users who clear their app's cache can delete the parameter files to save space, since they can be downloaded again the next time the wallet sends an outbound transaction. In other words, try to use the internal app cache directory, by default (or exclusively) if possible.

### Background
Sapling requires two fairly large files (`sapling-spend.params` and `sapling-output.params`) and the SDK looks for them in the default directory ([{context.cacheDir.absolutePath}/params](https://github.com/zcash/zcash-android-wallet-sdk/blob/96da0a9beaa92597bd4abdd74dce7c3098fbb86d/src/main/java/cash/z/ecc/android/sdk/Initializer.kt#L66)) . When they are missing, the SDK will automatically download them from  our google cloud instance: https://z.cash/downloads/
Allowing an attacker to easily modify these files is a security and privacy risk. At a bare minimum, the SDK should help developers manage this complexity by preventing them from storing these files in directorys that can be accessed by other apps.

The `SaplingParamTool` was created to make it a bit easier for developers to manage the necessary param files for doing proofs. One side-effect of these code changes is it turned the "destination directory" into a parameter, now making it possible for developers to supply any location they want for storing these files. We should address that by checking the input.

### Implementation details
* The simplest fix might be to modify the [fetchParams function](https://github.com/zcash/zcash-android-wallet-sdk/blob/96da0a9beaa92597bd4abdd74dce7c3098fbb86d/src/main/java/cash/z/ecc/android/sdk/tool/SaplingParamTool.kt#L55) to check the input `destinationDir` parameter and ensure that it does not reference a public location like the external files directory.
* An alternate solution might be to change the API so that the `destinationDir` is always a subdirectory of an appropriate parent folder, rather than an absolute path
    * SDK users should not be able to change the parent folder
    * the folder should be internal to the app (ideally, the internal cache directory)
    * the folder should be considered internal on all supported Android API levels (higher API levels sometimes protect directories that lower API levels did not)
* If the SDK is going to warn developers about this at run time, it should do so as early as possible. One good place might be in the `validate()` function that is [called during initialization](https://github.com/zcash/zcash-android-wallet-sdk/blob/96da0a9beaa92597bd4abdd74dce7c3098fbb86d/src/main/java/cash/z/ecc/android/sdk/Initializer.kt#L317-L321) because this will trigger very early.

**Comment by ccjernigan** [comment]
This was implemented by Honza, as we no longer give SDK clients the option of where to store the params files.
