### ISSUE TITLE
Connect BugSnag to Github

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#246]
As a developer, I'd like to connect our bugsnag instance to our github repositories so that we can make better use of all the integrations that it offers.

### Criteria
- [ ] our bugsnag instance is connected to the related github priorities
- [ ] optional (but recommended): related investigation is done to identify the primary benefits and workflow improvements we can get by connecting to our github instance. For instance, it might be possible to integrate bugsnag bugs into github issues and have them automatically get closed in bugsnag once they're closed on github or vice-versa.

### Implementation Details
* Right now we have bugsnag but it's not connected to any of our github repositories
* This should be a fairly simple task but it has stayed on the backlog since it is not urgent
* Labeled this as "good first issue" because it doesn't require any Zcash domain knowledge. However, it can only be completed by someone with access to the ECC bugsnag account so **it's a good issue for a new ECC employee but not a good issue for a 3rd party contributor.**

**Comment by ccjernigan** [comment]
This is not relevant for the SDK.
