### ISSUE TITLE
Remove Dependencies on jcenter

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#260]
**What is your feature request?**
Remove dependency on jcenter, since jcenter is deprecated.  The demo-app appears to depend on jcenter for one of our own artifacts.

This is non-urgent given that jcenter will continue hosting artifacts but eventually this migration will need to happen as new artifact versions can't be published to jcenter in the future.

**Comment by pacu** [comment]
I think this can already be worked on. 
Are there any changes needed on the reference wallet to support this or is maven central already adopted ?

**Comment by ccjernigan** [comment]
The packages that appear to be in jcenter are:
 - cash.z.ecc.android:kotlin-bip39:1.0.1
 - cash.z.ecc.android:zcash-android-sdk-testnet:1.2.1-beta02

**Comment by ccjernigan** [comment]
Do we have updated versions of those deployed to maven central or jitpack?

**Comment by pacu** [comment]
> cash.z.ecc.android:kotlin-bip39:1.0.1 
This one is the BIP 39 library we developed. It's probably not on maven central. 

> cash.z.ecc.android:zcash-android-sdk-testnet:1.2.1-beta02 
I don't think this should be ever needed the sdk should support both mainnet and testnet under the same artifact

**Comment by ccjernigan** [comment]
I found there's a newer version of bip39 on maven central, so that'll be easy.

Let me see what happens on removal of the testate artifact.

**Comment by ccjernigan** [comment]
The demo application is using a very old version of the SDK, and there are a number of public API changes in the SDK which for which the demo application needs to be updated.  I push some commits to a branch [here](https://github.com/ccjernigan/zcash-android-wallet-sdk/tree/260-jcenter), although the build is broken with be following issues that need to be resolved.

I haven't attempted fixing any of these yet, so I'm just providing an update on where this is currently.  I'll try to do a first pass at resolving these compile issues, although I might need some guidance if the new public APIs aren't immediately clear.

GetAddressFragment.kt
Unresolved reference: deriveViewingKeys
None of the following functions can be called with the arguments supplied:
public open fun deriveShieldedAddress(seed: ByteArray, network: ZcashNetwork, accountIndex: Int = ...): String defined in cash.z.ecc.android.sdk.tool.DerivationTool.Companion
public open fun deriveShieldedAddress(viewingKey: String, network: ZcashNetwork): String defined in cash.z.ecc.android.sdk.tool.DerivationTool.Companion
No value passed for parameter 'network'
None of the following functions can be called with the arguments supplied:
public open fun deriveShieldedAddress(seed: ByteArray, network: ZcashNetwork, accountIndex: Int = ...): String defined in cash.z.ecc.android.sdk.tool.DerivationTool.Companion
public open fun deriveShieldedAddress(viewingKey: String, network: ZcashNetwork): String defined in cash.z.ecc.android.sdk.tool.DerivationTool.Companion

GetBalanceFragment.kt
Unresolved reference: deriveViewingKeys
None of the following functions can be called with the arguments supplied:
public final fun importWallet(viewingKey: UnifiedViewingKey, birthdayHeight: Int? = ..., network: ZcashNetwork, host: String = ..., port: Int = ..., alias: String = ...): Initializer.Config defined in cash.z.ecc.android.sdk.Initializer.Config
public final fun importWallet(seed: ByteArray, birthdayHeight: Int? = ..., network: ZcashNetwork, host: String = ..., port: Int = ..., alias: String = ...): Initializer.Config defined in cash.z.ecc.android.sdk.Initializer.Config
Unresolved reference: server
Unresolved reference: balances
Unresolved reference: WalletBalance
Unresolved reference: WalletBalance
Unresolved reference: latestBalance
Unresolved reference: WalletBalance

GetPrivateKeyFragment.kt
The integer literal does not conform to the expected type ZcashNetwork
No value passed for parameter 'network'
Unresolved reference: deriveViewingKeys

ListTransactionsFragment.kt
Unresolved reference: PagedList
Unresolved reference: SdkInitializer
None of the following functions can be called with the arguments supplied:
public final fun importWallet(viewingKey: UnifiedViewingKey, birthdayHeight: Int? = ..., network: ZcashNetwork, host: String = ..., port: Int = ..., alias: String = ...): Initializer.Config defined in cash.z.ecc.android.sdk.Initializer.Config
public final fun importWallet(seed: ByteArray, birthdayHeight: Int? = ..., network: ZcashNetwork, host: String = ..., port: Int = ..., alias: String = ...): Initializer.Config defined in cash.z.ecc.android.sdk.Initializer.Config
Unresolved reference: server
None of the following functions can be called with the arguments supplied:
public open fun deriveShieldedAddress(seed: ByteArray, network: ZcashNetwork, accountIndex: Int = ...): String defined in cash.z.ecc.android.sdk.tool.DerivationTool.Companion
public open fun deriveShieldedAddress(viewingKey: String, network: ZcashNetwork): String defined in cash.z.ecc.android.sdk.tool.DerivationTool.Companion
Type mismatch: inferred type is TransactionAdapter<ConfirmedTransaction> but RecyclerView.Adapter<(raw) RecyclerView.ViewHolder!>? was expected
Unresolved reference: PagedList
Unresolved reference: submitList

TransactionAdapter.kt
Unresolved reference: PagedListAdapter
Unresolved reference: PagedListAdapter
'onCreateViewHolder' overrides nothing
'onBindViewHolder' overrides nothing
Unresolved reference: getItem

ListUtxosFragment.kt
Unresolved reference: PagedList
Unresolved reference: rpc
Unresolved reference: SdkInitializer
None of the following functions can be called with the arguments supplied:
public final fun importWallet(viewingKey: UnifiedViewingKey, birthdayHeight: Int? = ..., network: ZcashNetwork, host: String = ..., port: Int = ..., alias: String = ...): Initializer.Config defined in cash.z.ecc.android.sdk.Initializer.Config
public final fun importWallet(seed: ByteArray, birthdayHeight: Int? = ..., network: ZcashNetwork, host: String = ..., port: Int = ..., alias: String = ...): Initializer.Config defined in cash.z.ecc.android.sdk.Initializer.Config
Unresolved reference: SAPLING_ACTIVATION_HEIGHT
Unresolved reference: SAPLING_ACTIVATION_HEIGHT
Unresolved reference: LocalRpcTypes
No value passed for parameter 'network'
Type mismatch: inferred type is UtxoAdapter<ConfirmedTransaction> but RecyclerView.Adapter<(raw) RecyclerView.ViewHolder!>? was expected
Unresolved reference: PagedList
Unresolved reference: submitList

UtxoAdapter.kt
Unresolved reference: PagedListAdapter
Unresolved reference: PagedListAdapter
'onCreateViewHolder' overrides nothing
'onBindViewHolder' overrides nothing
Unresolved reference: getItem

SendFragment.kt
None of the following functions can be called with the arguments supplied:
public final fun importWallet(viewingKey: UnifiedViewingKey, birthdayHeight: Int? = ..., network: ZcashNetwork, host: String = ..., port: Int = ..., alias: String = ...): Initializer.Config defined in cash.z.ecc.android.sdk.Initializer.Config
public final fun importWallet(seed: ByteArray, birthdayHeight: Int? = ..., network: ZcashNetwork, host: String = ..., port: Int = ..., alias: String = ...): Initializer.Config defined in cash.z.ecc.android.sdk.Initializer.Config
Unresolved reference: server
No value passed for parameter 'network'
Unresolved reference: WalletBalance
Unresolved reference: balances
Unresolved reference: WalletBalance
