### ISSUE TITLE
SDK Fails to fallback to checkpoint on testnet build

### ISSUE THREAD

**Issue by pacu** [zcash/zcash-android-wallet-sdk#270]
**What is the bug?**
![image](https://user-images.githubusercontent.com/484008/132909667-846c9ee5-ee79-4aab-abae-86383d976900.png)
when using 1.3.0-beta.17, the testnet app fails to fall back to the latest local checkpoint.
Although beta18 fixes the issue because the checkpoint actually exists in the SDK's assets, this clearly indicates some flaw in the logic of the checkpoint selection 

**Solution**
Reproduce the issue, find out whether there are changes needed  or if this is just a data packaging error.

**Comment by nighthawk24** [comment]
Fixed in https://github.com/zcash/zcash-android-wallet-sdk/pull/250

Although it would help in creating another checkpoint for both `main-net` & `test-net` variants.
