### ISSUE TITLE
Remove Deprecated Usage of `ConflatedBroadcastChannel`

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#288]
**What is your feature request?**
Various internal parts of the SDK are using Kotlin's `ConflatedBroadcastChannel`, which has been deprecated.  The likely best replacement will be `MutableStateFlow`.  This is not urgent, as the API isn't being removed from Kotlin right away.

**How would this feature help you?**
Benefits of making this change include a simplified and more consistent internal interface for sharing observable state in the SDK.

During this transition, one item to be cautious about is explicitly setting the type for public exposed instances of these flows.

E.g.
```
private val _processorInfo = MutableStateFlow(ProcessorInfo())
val processorInfo: Flow = _processorInfo // Gives clients a read-only public API
```

**Comment by pacu** [comment]
thanks for rising this up
