### ISSUE TITLE
Add proguard consumer rules

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#302]
**What is your feature request?**
Our SDK will break if a consuming application uses R8 or ProGuard to optimize their app.  This is a feature request to add a proper `sdk-lib/proguard-consumer.txt` configuration file, along with modifying the `sdk-lib/build.gradle.kts` to include the consumer file in the resulting library.

This change will not enable R8 or ProGuard on the library, but it will enable apps consuming the SDK to enable R8 or ProGuard.

This will be a running list of rules that need to be added
 - Keep the JNI interfaces
 - Keep anything being used for reflection-based parsing (or remove reflection based parsing)
 - GRPC has some ProGuard rules: https://github.com/grpc/grpc-java/blob/master/android/proguard-rules.txt

**How would this feature help you?**
This will enable consuming applications to use R8 or ProGuard to optimize their apps.  This is something we will expect to use in our new wallet app.  A lot of the design of Jetpack Compose assumes that compile time optimization will be performed before an app is deployed to the app store.

This is not urgent—consumers of the SDK can work around this by disabling R8 or ProGuard (or they can implement their own keep rules).

**Comment by defuse** [comment]
It sounds like there's some code optimization stuff in addition to obfuscation. As we discussed in standup this may be worth doing to support (our or others') optimization of the apps, but obfuscating for obfuscation alone isn't worth doing.

**Comment by defuse** [comment]
It would be nice if our official app APKs are as easily reverse-engineerable as possible (to assist any security researchers looking at them!), so anything that heavily obfuscates rather than just being a performance optimization should probably be turned off in our apps that consume the SDK. 

Low-effort things to make the SDK compatible with consumers who want to obfuscate makes sense to do, though.
