### ISSUE TITLE
Internal-Security-Finding #2: No TLS security for connection to lightwalletd

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-android-wallet-sdk#33]
I'm sure this is a known issue, but raising it so it's tracked:

```
ManagedChannelBuilder.forAddress(host, port).usePlaintext().build()
```

**Comment by defuse** [comment]
It would be super cool if the API made it impossible to *not* use TLS.

**Comment by defuse** [comment]
As noted in the Bishop Fox audit report (issue 3), there is also no authentication as a result of this. Wallets / users will want to be able to pick a specific lightwallet server to connect to (or a set of them) and be guaranteed they are really talking to the real one(s).

**Comment by defuse** [comment]
I'm pretty sure we can close this since there's TLS now, right @gmale?

**Comment by gmale** [comment]
Yes!
