### ISSUE TITLE
Store database files in nobackup directory

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#343]
**What is the bug?**
The SDK stores large database files in the app's database directory.  These will be backed up if the user has system backups enabled.

Because these databases are regenerated based on the user's import with a wallet secret, these database should be excluded from backups.

It is also possible these backups could leak some user information to the backup provider.

**Solution**
Two possible solutions:
 - Add documentation for SDK consumers to manually exclude these files from backups.  This requires a manual step from SDK consumers, which could be easily missed.  This is a bit annoying, because the backup excludes configuration can't be provided programatically by the SDK.
 - Move the database files to the nobackup directory, which will mostly prevent them from being included in backups.  This requires no effort from SDK consumers, although it will be a more complex implementation since the SDK itself needs to do this migration during first launch after an upgrade.

**Comment by pacu** [comment]
Is it possible to let developers choose the URL for the databases? I don't think the SDK must impose any of that.

**Comment by ccjernigan** [comment]
The existence of databases is an internal implementation detail of our SDK, because we might add or eliminate files or switch database formats in the future.

To make this better, I think we should have 1 filesystem directory that's owned by the SDK, with a well defined default path that's namespaced to avoid conflicts (e.g. co.electriccoin.zcash or something else with a package name).  The SDK can then do whatever it wants inside that directory and consumers shouldn't touch that directory's contents.

I'm open to having that path A. have a default value B. documenting that default value, and C. allowing clients to change that default value if necessary.

Thoughts?

**Comment by ccjernigan** [comment]
> @ccjernigan our SDK works with 3 databases (named e.g. `PendingTransactions.db`, `ZcashSdk_mainnet_Cache.db`, `ZcashSdk_mainnet_Data.db`).
> 
> 1. Does this request apply to all of those 3 databases? Or just to the Cache and Data one?
> 2. The PendingTransactions and the ZcashSdk_mainnet_Data databases seem to be pretty small, but the Cache one appears to be quite big, e.g. over 1GB in case of scanning the whole blockchain. I assume we want to do the copy and delete original db files before the whole SDK initialization, and thus do it blocking. Do we want to create some new SDK state (like repairing) or something similar to let callers know what is happening?

1. All three
2. The operation should be relatively quick—we're just doing a file rename within the same filesystem so it is just metadata changing rather than copying the files.  Since we're in a suspend function already, we'll hop over to the IO context and just require callers to wait while we update the metadata.
