### ISSUE TITLE
Remove Explicit GSON Usage

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#377]
**What is your feature request?**
The JSON parsing for the checkpoints is using the GSON library.  This request is to remove this usage of GSON in favor of Android's built-in JSON parsing.

**How would this feature help you?**
There's no need for us to rely on GSON for such a very small usage.  Removing this will help prevent GSON from spreading elsewhere in our codebase, as it really probably isn't needed.

We'll still use GSON transitively through grpc, but at least it'll be contained there and will be easy to remove in the future if we should decide to do so.

We have a JSON parser implemented already in https://github.com/zcash/secant-android-wallet/blob/main/sdk-ext-lib/src/main/java/cash/z/ecc/sdk/model/WalletBirthdayExt.kt

**Comment by pacu** [comment]
Great catch. Also, it's possible that GRPC will eventually go the same path and ditch that dependency as well.
