### ISSUE TITLE
JVM Args can Cause Out of Memory

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#427]
### Describe the issue
The current JVM args set the memory limit to 2gb, but this clears a Gradle default for the maxmetaspace argument

See https://github.com/gradle/gradle/issues/19750

The fix is to change the `gradle.properties` to be `org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m`

This will match the settings in the Secant Wallet repo as well.

**Comment by geffenz** [comment]
@ccjernigan who needs to improve this or is the change done and we can close this ticket?

**Comment by ccjernigan** [comment]
waiting on @pacu to approve PR #428
