### ISSUE TITLE
Verify where validate_combined_chain is used

### ISSUE THREAD

**Issue by str4d** [zcash/zcash-android-wallet-sdk#48]
From zcash/librustzcash#84:
> Where is `validate_combined_chain` used? I can't find its use in the Rust crates or the SDK. (I was looking for it because I was concerned about threading/TOCTTOU bugs.)

**Comment by gmale** [comment]
Can this be closed?

It's currently [used here](https://github.com/zcash/zcash-android-wallet-sdk/blob/452540fb2fb206f403e13bcafbf41c19f456f96b/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt#L358).

**Comment by gmale** [comment]
@str4d Can this be closed?

It's currently [used here](https://github.com/zcash/zcash-android-wallet-sdk/blob/452540fb2fb206f403e13bcafbf41c19f456f96b/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt#L358).
