### ISSUE TITLE
Bring in UA-specific migrations

### ISSUE THREAD

**Issue by str4d** [zcash/zcash-android-wallet-sdk#529]
#15 will enable new wallets generated by this library to be compatible with UAs. Existing wallets will require database migrations, which we are planning to build in zcash/librustzcash#489. That PR can't be brought in until after #16.

Alternatively, we do have some migration support already in this SDK, so we could instead apply the equivalent migrations from zcash/librustzcash#489 here separately.

**Comment by nuttycom** [comment]
Closed in #717
