### ISSUE TITLE
Demo-app crashes while getting latest height without internet connection 

### ISSUE THREAD

**Issue by HonzaR** [zcash/zcash-android-wallet-sdk#542]
### Describe the issue
Demo-app crashes while getting the latest height without internet connection. Here is a list of the demo-app functions, which cause the app crashing when run without the internet connection (there can be possibly more of them):

- Side menu -> Get Latest Height
- Side menu -> Get Block Range -> Apply
- Side menu -> List UTXOs -> Load Transactions

#### If so, please list the steps to reproduce below:
1. Install demo-app with the latest main branch commit 
2. Ensure the device has no internet connection enabled
3. Open the demo-app
4. Side menu -> Get Latest Height
5. Now the app crashes

### Actual behavior + errors
When the app crashes, it unfortunately doesn't give us many logs, just:
```
FATAL EXCEPTION: main
Process: cash.z.ecc.android.sdk.demoapp.mainnet, PID: 25132
```

Tested on:
- App Version: v1.1.0 Mainnet
- Android Version: SDK 29 & 32
- Device: Real device & emulator
- Commit: Current main branch `8f59a20`, tested also on `e2770d8` from 5/5/2022 (applies for both)

### Any extra information that might be useful in the debugging process.
Doesn't matter if the device runs on the first time with connection and then without it, or without the connection on the first run, the crash happens in both cases.

**Comment by geffenz** [comment]
While not blocked, a refactor while possibly modify this bug - so skipped for a sprint or two.

**Comment by HonzaR** [comment]
https://github.com/zcash/zcash-android-wallet-sdk/pull/675 partially solves this trouble. GetLatestHeight works correctly now. Other problematic calls will be solved by followup PRs.
