### ISSUE TITLE
Use correct coin type during initialization

### ISSUE THREAD

**Issue by str4d** [zcash/zcash-android-wallet-sdk#57]
In the preview branch (which I believe is the latest code), the Rust backend hard-codes the testnet coin type:

https://github.com/zcash/zcash-android-wallet-sdk/blob/bb824450b0b560810e8718cad9f46cbef0e4a722/src/main/rust/lib.rs#L97

It should instead use the `COIN_TYPE` constant from `zcash_client_backend::constants`, conditionally imported in the same way that `HRP_SAPLING_EXTENDED_SPENDING_KEY` is.

**Comment by gmale** [comment]
I believe this no longer applies and can be closed but I'd need to verify.

**Comment by gmale** [comment]
This definitely has been addressed because it was uncovered and fixed as part of a bug a while back. If it re-surfaces we can open another ticket but I'm certain it is addressed so closing.
