### ISSUE TITLE
Convert ZcashNetwork to Interface

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#593]
## Is your feature request related to a problem? Please describe.
ZcashNetwork is currently an enum with hardcoded values.

This makes it difficult to implement certain tests (e.g. darkside) as well as supporting changes in the host/port of the server.

## Describe the solution you'd like
Convert `ZcashNetwork` to an interface and then provide factory methods for constructing networks with the default values.

For example:

```
interface ZcashNetwork {
    val id: Int
    val networkName: String
    val saplingActivationHeight: BlockHeight
    val host: String
    val port: Int
}
```

```
object ZcashNetworkFactory {
    fun newTestnetNetwork(host: String = "testnet.lightwalletd.com", port: Int = 9067) = ZcashNetwork(0, "testnet", 280_000, host, port)
    fun newMainnetNetwork(host: String = "mainnet.lightwalletd.com", port: Int = 9067) = ZcashNetwork(1, "mainnet", 419_200, host, port)
}
```

**Comment by pacu** [comment]
I somewhat regret having SDK constants as an interface. I've found that Protocol Witnesses are a much more testable and flexible approach for this kind of things. 

some resources:
https://www.youtube.com/watch?v=3BVkbWXcFS4
https://www.pointfree.co/collections/protocol-witnesses/alternatives-to-protocols/ep33-protocol-witnesses-part-1
