### ISSUE TITLE
Replace ComputableFlow and asFlow() obsolete Coroutine usage

### ISSUE THREAD

**Issue by HonzaR** [zcash/zcash-android-wallet-sdk#658]
## Is your feature request related to a problem? Please describe.
Our SDK implementation uses an obsolete Coroutine API like:

- `ConflatedBroadcastChannel<T>`
- `computationChannel.asFlow()`
- `computationChannel.send()`
- `computationChannel.cancel()`

in the class `cash.z.ecc.android.sdk.internal.ext.android.ComputableFlow`

## Describe the solution you'd like
Note: This API is obsolete since 1.5.0. It will be deprecated with warning in 1.6.0 and with error in 1.7.0. It is replaced with `StateFlow`.

## Additional context
We suppress this warning with `@ObsoleteCoroutinesApi` for now.

**Warnings**: 
- 'asFlow(): Flow<T>' is deprecated. 'BroadcastChannel' is obsolete and all corresponding operators are deprecated in the favour of StateFlow and SharedFlow
- This declaration needs opt-in. Its usage should be marked with '@kotlinx.coroutines.ObsoleteCoroutinesApi' or '@OptIn(kotlinx.coroutines.ObsoleteCoroutinesApi::class)'

**Comment by ccjernigan** [comment]
Related but separate issue: https://github.com/zcash/zcash-android-wallet-sdk/issues/288
