### ISSUE TITLE
Use suspending functions for networking

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#674]
## Is your feature request related to a problem? Please describe.
`CompactBlockProcessor` is using blocking GRPC calls, which means each network call is wrapped in a `withContext`.  This makes reasoning about network connections very complex.

## Describe the solution you'd like
Switch `CompactBlockProcessor` to use `CoroutineLightWalletClient`.

**Comment by HonzaR** [comment]
Note about `FileCompactBlockRepositoryTest#getLatestHeightTest` -> `FileCompactBlockRepository#write` refactoring. Write function could work with flow as well.
