### ISSUE TITLE
Transactions - PendingTransaction.isExpired - test for off-by-one error here

### ISSUE THREAD

**Issue by HonzaR** [zcash/zcash-android-wallet-sdk#687]
## Is your feature request related to a problem? Please describe.
Filling an additional issue to provide a link to the code base TODO occurrence.

We'd like to test for off-by-one error here. Should we use <= or < in `PendingTransaction.isExpired`?

**Comment by pacu** [comment]
this can probably be closed  @ccjernigan

**Comment by ccjernigan** [comment]
Closing because pending transactions are being removed.
