### ISSUE TITLE
Switch to Rust for migrations

### ISSUE THREAD

**Issue by str4d** [zcash/zcash-android-wallet-sdk#704]
https://github.com/zcash/librustzcash/issues/369 added a database migratrion system to `zcash_client_sqlite`. We then used it to implement the autoshielding-related migrations in https://github.com/zcash/librustzcash/issues/594.

Rather than copying the migrations into Room, we want to use the Rust migrations directly.

**Comment by nuttycom** [comment]
Closed by #705 and #730
