### ISSUE TITLE
Consider preventing multiple synchronizer instances

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#742]
## Is your feature request related to a problem? Please describe.
If two synchronizer instances are running on the same Zcash network and alias, they will conflict with eachother.

## Describe the solution you'd like
During Synchronizer startup, consider having some global state that uses network+alias as a key to determine whether another synchronizer is running the same key.  During synchronizer teardown, clear the state.  To make this work robustly, a mutex will be needed.

**Comment by pacu** [comment]
Why not Initializer ? 
![image](https://user-images.githubusercontent.com/484008/197231082-0e906790-7ad4-4f6b-96ed-712b688fefa8.png)

**Comment by ccjernigan** [comment]
> Why not Initializer ?
> ![image](https://user-images.githubusercontent.com/484008/197231082-0e906790-7ad4-4f6b-96ed-712b688fefa8.png)

We killed the Initializer on Android! 🔨
