### ISSUE TITLE
Add internal recipient information to PendingTransactionEntity

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#748]
## Describe the solution you'd like
 - Add a migration to PendingTransaction database to support internal accounts as a destination
 - When creating a shielding transaction, store an internal account instead of an address

**Comment by pacu** [comment]
this can probable be closed @ccjernigan

**Comment by ccjernigan** [comment]
Closing because pending transactions have been removed.
