### ISSUE TITLE
Download and scan blocks in parallel

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#768]
## Is your feature request related to a problem? Please describe.
The SDK currently downloads all blocks, then processes them. This is slow and requires an enormous amount of disk space.

## Describe the solution you'd like
Process blocks shortly after they are downloaded, then delete them. Limit the total number of queued blocks for processing so that the SDK doesn’t consume nearly unbounded amounts of disk space.

## Additional context
Detailed analyse was made in the iOS ticket https://github.com/zcash/ZcashLightClientKit/issues/442.

**Comment by HonzaR** [comment]
Closing as done.
