### ISSUE TITLE
Get zecwallet-light's version of lightwalletd running locally

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#80]
Aditya's lightwalletd has mainnet support and using it will help us to transition the SDK to mainnet faster.

Requires:
- pulling the latest version of zcashd and recompiling
- configuring the zcashd node for mainnet + insight and syncing (6+ hours)
- cloning, configuring and running aditya's lightwalletd
  - configure for mainnet without TLS support to start, then try TLS once that's working

**Comment by braddmiller** [comment]
Hey guys, work together to get Kevin and Pacu synced up on mainnet to get this ticket moving.
