### ISSUE TITLE
Network Upgrade Awareness

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet-sdk#81]
Story: As a developer, using the library, I would like to build transactions that can be successfully broadcast to the network I am on so that the wallet I build handles network upgrades more robustly.

**Comment by gmale** [comment]
This is probably phrased too broadly. Significant work has been done here and transaction creation is now height-based. Improvements could be made for handling network upgrades more robustly but that's a broader scope of work. Closing this for now. We can add issues for improving the upgrade flow, as needed.
