### ISSUE TITLE
Kotlin 1.7.21

### ISSUE THREAD

**Issue by HonzaR** [zcash/zcash-android-wallet-sdk#820]
For a Gradle dependency:
1. Update the dependency version in the root `gradle.properties`
1. Update the dependency locks
    1. For Gradle plugins: `./gradlew dependencies --write-locks`
    1. For Gradle dependencies: `./gradlew resolveAll --write-locks`
1. Verify no unexpected entries appear in the lockfiles. _A supply chain attack could occur during this stage. The lockfile narrows the supply chain attack window to this very moment (as opposed to every time a build occurs)_
1. Are there any new APIs or possible migrations for this dependency?

 - org.jetbrains.kotlin:kotlin-reflect [1.7.20 -> 1.7.21]
     https://kotlinlang.org/
 - org.jetbrains.kotlin:kotlin-stdlib [1.7.20 -> 1.7.21]
     https://kotlinlang.org/
 - org.jetbrains.kotlin:kotlin-test [1.7.20 -> 1.7.21]
     https://kotlinlang.org/

**Comment by ccjernigan** [comment]
Just bump to 1.7.21 since 1.7.22 isn't a real release.  (IntelliJ plugin won't be updated for it)
