### ISSUE TITLE
Update Rust Crates to fix empty `get_transparent_balance()` error 

### ISSUE THREAD

**Issue by pacu** [zcash/zcash-android-wallet-sdk#824]
Please update `Cargo.toml` dependencies to a commit that includes librustzcash commit `2ad40ca5abe6d57a05cd3a3ccb31
c1ed5f88ca56` (tag: zcash_client_sqlite-0.4.2) which fixes an error on the sqlite crate where an error would be thrown if the transparent balance is queried on an empty UTXOS table.

**Comment by str4d** [comment]
#806 bumps the SDK from 0.4.0 to 0.4.1; I can either update the PR to bump to 0.4.2 instead, or the bump can be done after #806 is merged.
