### ISSUE TITLE
Extremely noisy logging

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#894]
Something changed with a recent update to the SDK and the logs are being drowned out by this line
```
01-24 09:04:53.916 27353 27534 W System.err: @TWIG 01/24/23 09:04:53.915000000[FrameworkSQLiteOpenHelper:166](#downloading)    Database: zcash_sdk_testnet_cache.sqlite3 in directory: /data/user/0/co.electriccoin.zcash.testnet.debug/no_backup/co.electricoin.zcash
```

**Comment by HonzaR** [comment]
It comes from `cash.z.ecc.android.sdk.internal.NoBackupContextWrapper#getDatabasePath`, which hasn't been changed recently. We need to dive more into the latest merged changes.

**Comment by HonzaR** [comment]
Until fixed, use `package:mine -message:NoBackupContextWrapper.getDatabasePath` as filter in the new Android Studio Logcat panel to filter it out, if needed.
