### ISSUE TITLE
Improve sync status reporting 

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#967]
## Is your feature request related to a problem? Please describe.
Clients have a hard time displaying status to the user, because percentages of a large number of blocks don't reliably convey progress.

## Describe the solution you'd like
There are two elements to this feature:
1. Have a simplified set of states reported by the synchronizer
    1. Up to date
    2. Syncing
    3. Refreshing
    4. Error
2. Improve the data incorporated into each state.  Syncing is the most important, and should have the following information
    1. Sync session ID - an opaque globally unique string that changes each time a new sync starts. This is implemented as a string, but as an implementation it could be a UUID
    2. Sync start time
    3. Height of last block downloaded
    4. Timestamp of last block scanned
    5. Height of target block (e.g. tip of chain).  This may change repeatedly over time as the chain grows during a sync
    6. Timestamp of target block

Clients can then determine whether to show users a percentage, date of last synced block, height of last synced block, or something else.  With the use of sync session ID and timestamp, clients can also better differentiate and remember whether sync has ever completed and decide how to display to the user when an incomplete sync is resumed in the future.

**Comment by pacu** [comment]
I'd say that we do 2 and then 1.

**Comment by nuttycom** [comment]
This is now subsumed by #1186
